package telegram;

/**
 * Created by pouria on 2/9/17.
 */
public class BotConfig {
    public static final String BOT_TOKEN = "<token>";  // the token generated by botfather
    public static final String BOT_USERNAME = "<userName>"; // the bot username without @
    public static final long GROUP_ID = 0000;  // the chat_id of the telegram group assigned for the 20 question match
}
